In [0]:
import torch

In [0]:
def activation(x):
  return 1/(1+torch.exp(-x))

In [0]:
torch.manual_seed(7)
features = torch.randn((1,5))
weights = torch.randn_like(features)
bias = torch.randn((1,1))

In [0]:
output = activation(torch.mm(features,weights.T)+bias)

In [5]:
output.shape

torch.Size([1, 1])

In [6]:
output

tensor([[0.1595]])

In [0]:
torch.manual_seed(7)
features = torch.randn((1,3))
n_input = features.shape[1]
n_hidden = 2
n_output = 1
W1 = torch.randn((n_input,n_hidden))
W2 = torch.randn((n_hidden,n_output))
B1 = torch.randn((1,n_hidden))
B2 = torch.randn((1,n_output))

In [8]:
output1 = activation(torch.mm(features,W1)+B1)
output1.shape


torch.Size([1, 2])

In [9]:
output2 = activation( torch.mm(output1,W2)+B2)
output2.shape

torch.Size([1, 1])

In [10]:
output2

tensor([[0.3171]])

### **Numpy and PyTorch**

In [0]:
import numpy as np

In [12]:
a = np.random.rand(4,3)
a

array([[0.32390887, 0.04227979, 0.36771231],
       [0.91248407, 0.27319432, 0.6049606 ],
       [0.54276594, 0.13784339, 0.00928058],
       [0.4094927 , 0.9963272 , 0.98770939]])

In [13]:
b = torch.from_numpy(a)
b

tensor([[0.3239, 0.0423, 0.3677],
        [0.9125, 0.2732, 0.6050],
        [0.5428, 0.1378, 0.0093],
        [0.4095, 0.9963, 0.9877]], dtype=torch.float64)

In [14]:
b.mul_(2)

tensor([[0.6478, 0.0846, 0.7354],
        [1.8250, 0.5464, 1.2099],
        [1.0855, 0.2757, 0.0186],
        [0.8190, 1.9927, 1.9754]], dtype=torch.float64)

In [15]:
a

array([[0.64781773, 0.08455959, 0.73542462],
       [1.82496815, 0.54638864, 1.20992121],
       [1.08553189, 0.27568677, 0.01856115],
       [0.8189854 , 1.99265441, 1.97541878]])